apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-app-docmost.yaml
  - namespace-app-homepage.yaml
  - namespace-app-immich.yaml
  - namespace-app-nextcloud.yaml
  - namespace-authentik.yaml
  - coredns-configmap.yaml
  - metallb
  - envoy-gateway
  - external-dns
  - external-secrets
  - cloudnative-pg
  - authentik
  - garage
  - garage-ui
  - longhorn
  - volume-snapshots
  - volsync
  - kube-prometheus-stack
  - victorialogs
  - fluent-bit
  - cloudflared
  - status
