apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garage-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts/
      chart: app-template
      targetRevision: 4.6.2
      helm:
        releaseName: garage-ui
        valueFiles:
          - $values/kubernetes/infra/garage-ui/values.yaml
    - repoURL: https://github.com/NoBadDays/erasmus.works.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: garage-ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
