apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  disableNameSuffixHash: true
configMapGenerator:
  - name: authentik-blueprint-argocd
    namespace: authentik
    files:
      - blueprints/argocd.yaml
  - name: authentik-blueprint-envoy-gateway
    namespace: authentik
    files:
      - blueprints/envoy-gateway.yaml
  - name: authentik-blueprint-grafana
    namespace: authentik
    files:
      - blueprints/grafana.yaml
  - name: authentik-blueprint-nextcloud
    namespace: authentik
    files:
      - blueprints/nextcloud.yaml
resources:
  # Core
  - application.yaml
  - externalsecrets.yaml
  - postgres.yaml
  - blueprint-immich-configmap.yaml

  # Storage
  - pvc-media.yaml

  # Networking
  - networkpolicy.yaml
  - backendtrafficpolicy.yaml
  - httproute.yaml
