authentik:
  existingSecret:
    secretName: authentik-env

postgresql:
  enabled: false

serviceAccount:
  create: false

server:
  initContainers:
    - name: wait-for-postgres
      image: busybox:1.37
      command:
        - sh
        - -c
        - until nc -z authentik-postgres-rw.apps.svc.cluster.local 5432; do sleep 2; done
  volumes:
    - name: media
      persistentVolumeClaim:
        claimName: authentik-media
  volumeMounts:
    - name: media
      mountPath: /data
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

worker:
  initContainers:
    - name: wait-for-postgres
      image: busybox:1.37
      command:
        - sh
        - -c
        - until nc -z authentik-postgres-rw.apps.svc.cluster.local 5432; do sleep 2; done
  volumes:
    - name: media
      persistentVolumeClaim:
        claimName: authentik-media
    - name: blueprint-argocd
      configMap:
        name: authentik-blueprint-argocd
    - name: blueprint-immich
      configMap:
        name: authentik-blueprint-immich
    - name: blueprint-nextcloud
      configMap:
        name: authentik-blueprint-nextcloud
  volumeMounts:
    - name: media
      mountPath: /data
    - name: blueprint-argocd
      mountPath: /blueprints/argocd.yaml
      subPath: argocd.yaml
    - name: blueprint-immich
      mountPath: /blueprints/immich.yaml
      subPath: immich.yaml
    - name: blueprint-nextcloud
      mountPath: /blueprints/nextcloud.yaml
      subPath: nextcloud.yaml
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
