authentik:
  existingSecret:
    secretName: authentik-env

postgresql:
  enabled: false

serviceAccount:
  create: false

server:
  deploymentStrategy:
    type: Recreate
  initContainers:
    - name: wait-for-postgres
      image: busybox:1.37
      command:
        - sh
        - -c
        - until nc -z authentik-postgres-rw.apps.svc.cluster.local 5432; do sleep 2; done
  volumes:
    - name: media
      persistentVolumeClaim:
        claimName: authentik-media
  volumeMounts:
    - name: media
      mountPath: /data
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 768Mi

worker:
  deploymentStrategy:
    type: Recreate
  initContainers:
    - name: wait-for-postgres
      image: busybox:1.37
      command:
        - sh
        - -c
        - until nc -z authentik-postgres-rw.apps.svc.cluster.local 5432; do sleep 2; done
  volumes:
    - name: media
      persistentVolumeClaim:
        claimName: authentik-media
    - name: blueprints
      projected:
        sources:
          - configMap:
              name: authentik-blueprint-argocd
              items:
                - key: argocd.yaml
                  path: argocd.yaml
          - configMap:
              name: authentik-blueprint-envoy-gateway
              items:
                - key: envoy-gateway.yaml
                  path: envoy-gateway.yaml
          - configMap:
              name: authentik-blueprint-grafana
              items:
                - key: grafana.yaml
                  path: grafana.yaml
          - configMap:
              name: authentik-blueprint-immich
              items:
                - key: immich.yaml
                  path: immich.yaml
          - configMap:
              name: authentik-blueprint-nextcloud
              items:
                - key: nextcloud.yaml
                  path: nextcloud.yaml
  volumeMounts:
    - name: media
      mountPath: /data
    - name: blueprints
      mountPath: /blueprints
      readOnly: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 768Mi
