apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volume-snapshots
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://piraeus.io/helm-charts/
    chart: snapshot-controller
    targetRevision: 5.0.2
    helm:
      releaseName: snapshot-controller
      values: |
        installCRDs: true
        controller:
          replicaCount: 1
        volumeSnapshotClasses:
          - name: longhorn-snapshot-vsc
            annotations:
              snapshot.storage.kubernetes.io/is-default-class: "true"
            driver: driver.longhorn.io
            deletionPolicy: Delete
            parameters:
              type: snap
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
