apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - application.yaml
  - nfs-backup-pv.yaml
  - nfs-backup-pv-app-docmost.yaml
  - nfs-backup-pvc-app-docmost.yaml
  - nfs-backup-pv-app-nextcloud.yaml
  - nfs-backup-pvc-app-nextcloud.yaml
