apiVersion: v1
kind: PersistentVolume
metadata:
  name: volsync-backups-app-nextcloud
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  nfs:
    server: 192.168.20.40
    path: /mnt/tank/k8s-volsync
