apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volsync-repository
  namespace: app-nextcloud
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: volsync-backups-app-nextcloud
