- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: homelab
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
