apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docmost-app-secret
  namespace: docmost
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: docmost-app-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: appSecret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: docmost-app-secret
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docmost-postgresql-secret
  namespace: docmost
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: docmost-postgresql-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: postgresql-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: docmost-postgresql-password
        metadataPolicy: None
