apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docmost-postgres-auth
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: docmost-postgres-auth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      data:
        username: docmost
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: docmost-postgres-password
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docmost-app-secrets
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: docmost-app-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        app-secret: "{{ .app_secret }}"
        database-url: postgresql://docmost:{{ .password }}@docmost-postgres-rw.apps.svc.cluster.local:5432/docmost?schema=public
        smtp-password: "{{ .smtp_password }}"
  data:
    - secretKey: app_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: docmost-app-secret
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: docmost-postgres-password
        metadataPolicy: None
    - secretKey: smtp_password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: smtp2go-password
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docmost-postgres-backup-s3
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: docmost-postgres-backup-s3
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        ACCESS_KEY_ID: "GKb4160962a499b32b4ffa0104"
        ACCESS_SECRET_KEY: "{{ .access_secret_key }}"
  data:
    - secretKey: access_secret_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: docmost-cnpg-backup-secret-access-key
        metadataPolicy: None
