apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: docmost-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  monitoring:
    enablePodMonitor: true
  storage:
    size: 10Gi
    storageClass: longhorn
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-docmost
      endpointURL: http://garage.garage.svc.cluster.local:3900
      serverName: docmost-postgres
      s3Credentials:
        accessKeyId:
          name: docmost-postgres-backup-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: docmost-postgres-backup-s3
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
    retentionPolicy: "30d"
  bootstrap:
    initdb:
      database: docmost
      owner: docmost
      secret:
        name: docmost-postgres-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: docmost-postgres-backup
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  schedule: "0 0 3 * * *" # every day at 3:00am
  immediate: true
  backupOwnerReference: cluster
  cluster:
    name: docmost-postgres
