apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-data-restore
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: docmost-data-restore
  namespace: apps
spec:
  trigger:
    manual: restore-once
  restic:
    repository: docmost-data-restic-config
    destinationPVC: docmost-data-restore
    copyMethod: Direct
