fullnameOverride: docmost

image:
  tag: 0.23.2

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

docmost:
  appUrl: https://docmost.erasmus.works

postgresql:
  image:
    repository: postgres
    tag: 18.0-alpine
    pullPolicy: IfNotPresent
  auth:
    database: docmost
    username: docmost
    password: placeholder-managed-by-external-secret
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi

redis:
  image:
    repository: redis
    tag: 8.2.3-alpine
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
  persistence:
    enabled: false
