apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: cloudnative-pg
      app.kubernetes.io/name: cloudnative-pg
  endpoints:
    - port: metrics
      interval: 30s
