apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backendtrafficpolicy.yaml
  - externalsecrets.yaml
  - networkpolicy.yaml
  - pv-media-nfs.yaml
  - pvc-ml-cache.yaml
  - postgres.yaml
  - httproute.yaml
