apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:14.22-1.1.1
  instances: 1
  resources:
    requests:
      cpu: "1"
      memory: 512Mi
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - talos-siw-gdf
  monitoring:
    enablePodMonitor: true
  postgresql:
    shared_preload_libraries:
      - vchord.so
  storage:
    size: 20Gi
    storageClass: longhorn
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-immich
      endpointURL: http://garage.garage.svc.cluster.local:3900
      serverName: app-immich-postgres
      s3Credentials:
        accessKeyId:
          name: immich-postgres-backup-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: immich-postgres-backup-s3
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
    retentionPolicy: "30d"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-postgres-backup
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  schedule: "0 30 3 * * *" # every day at 3:30am
  immediate: true
  backupOwnerReference: cluster
  cluster:
    name: immich-postgres
