defaultPodOptions:
  automountServiceAccountToken: false

immich:
  metrics:
    enabled: true
  persistence:
    library:
      existingClaim: immich-media

server:
  controllers:
    main:
      containers:
        main:
          image:
            tag: v2.6.3
          env:
            TZ: Europe/Amsterdam
            IMMICH_TRUSTED_PROXIES: 10.244.0.0/16
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - secret: immich-app-secrets

machine-learning:
  persistence:
    cache:
      enabled: true
      existingClaim: immich-ml-cache
  controllers:
    main:
      containers:
        main:
          image:
            tag: v2.6.3
          env:
            TZ: Europe/Amsterdam
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: "6"
              memory: 6Gi

valkey:
  enabled: true
  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: longhorn
  controllers:
    main:
      containers:
        main:
          securityContext:
            allowPrivilegeEscalation: false
