defaultPodOptions:
  automountServiceAccountToken: false
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - talos-siw-gdf

immich:
  metrics:
    enabled: true
  persistence:
    library:
      existingClaim: immich-media

server:
  controllers:
    main:
      strategy: Recreate
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-server
            tag: v2.7.5
          env:
            TZ: Europe/Amsterdam
            IMMICH_TRUSTED_PROXIES: 10.244.0.0/16
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - secret: immich-app-secrets
          resources:
            requests:
              cpu: 250m
              memory: 768Mi

machine-learning:
  persistence:
    cache:
      enabled: true
      existingClaim: immich-ml-cache
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-machine-learning
            tag: v2.7.5
          env:
            TZ: Europe/Amsterdam
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: "6"
              memory: 6Gi

valkey:
  enabled: true
  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: longhorn
  controllers:
    main:
      containers:
        main:
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
