apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: affine
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/NoBadDays/erasmus.works.git
    targetRevision: main
    path: kubernetes/apps/affine
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
