apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docmost
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://acidsugarx.github.io/helm-open
      chart: docmost
      targetRevision: 0.1.3
      helm:
        releaseName: docmost
        valueFiles:
          - $values/kubernetes/apps/docmost/values.yaml
    - repoURL: https://github.com/NoBadDays/erasmus.works.git
      targetRevision: main
      ref: values
      path: kubernetes/apps/docmost
  destination:
    server: https://kubernetes.default.svc
    namespace: docmost
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: docmost-app-secret
      namespace: docmost
      jsonPointers:
        - /data
        - /metadata/annotations
        - /metadata/labels
        - /metadata/ownerReferences
    - group: ""
      kind: Secret
      name: docmost-postgresql-secret
      namespace: docmost
      jsonPointers:
        - /data
        - /metadata/annotations
        - /metadata/labels
        - /metadata/ownerReferences
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
