apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  sources:
    - repoURL: ghcr.io/immich-app/immich-charts
      chart: immich
      targetRevision: 0.11.0
      helm:
        releaseName: immich
        valueFiles:
          - $values/kubernetes/apps/immich/values.yaml
    - repoURL: https://github.com/ErasmusAndre/erasmus.works.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/ErasmusAndre/erasmus.works.git
      targetRevision: main
      path: kubernetes/apps/immich
  destination:
    server: https://kubernetes.default.svc
    namespace: app-immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
