controllers:
  garage:
    initContainers:
      init-storage:
        image:
          repository: busybox
          tag: 1.37
        command:
          - sh
          - -c
          - mkdir -p /var/lib/garage/data /var/lib/garage/meta
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
    containers:
      app:
        image:
          repository: dxflrs/garage
          tag: v2.3.0@sha256:866bd13ed2038ba7e7190e840482bc27234c4afaf77be8cfa439ae088c1e4690
        command:
          - /garage
        args:
          - server
        envFrom:
          - secretRef:
              name: garage-secrets
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 50m
            memory: 64Mi

service:
  app:
    ports:
      s3:
        port: 3900
      rpc:
        port: 3901
      admin:
        port: 3903

persistence:
  config:
    enabled: true
    type: configMap
    name: garage-config
    globalMounts:
      - path: /etc/garage.toml
        subPath: garage.toml
        readOnly: true
  storage:
    enabled: true
    type: nfs
    server: 192.168.20.40
    path: /mnt/tank/k8s-garage
    globalMounts:
      - path: /var/lib/garage
  tmp:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /tmp
