apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      name: nextcloud-html
      namespace: app-nextcloud
      jsonPointers:
        - /spec/volumeName
    - group: postgresql.cnpg.io
      kind: Cluster
      name: nextcloud-postgres
      namespace: app-nextcloud
      jsonPointers:
        - /spec/bootstrap
  sources:
    - repoURL: https://nextcloud.github.io/helm/
      chart: nextcloud
      targetRevision: 9.0.3
      helm:
        releaseName: nextcloud
        valueFiles:
          - $values/kubernetes/apps/nextcloud/values.yaml
    - repoURL: https://github.com/ErasmusAndre/erasmus.works.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/ErasmusAndre/erasmus.works.git
      targetRevision: main
      path: kubernetes/apps/nextcloud
  destination:
    server: https://kubernetes.default.svc
    namespace: app-nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
