apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victorialogs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts/
      chart: victoria-logs-single
      targetRevision: 0.11.31
      helm:
        releaseName: victorialogs
        valueFiles:
          - $values/kubernetes/infra/victorialogs/values.yaml
    - repoURL: https://github.com/NoBadDays/erasmus.works.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
