apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victorialogs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-logs-single
    targetRevision: 0.11.29
    helm:
      releaseName: victorialogs
      values: |
        vector:
          enabled: false

        server:
          replicaCount: 1
          fullnameOverride: victorialogs
          retentionPeriod: 14d
          service:
            clusterIP: ""
          persistentVolume:
            enabled: true
            storageClassName: longhorn
            size: 10Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
