apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-authentik-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        dex.authentik.clientSecret: "{{ .argocd_oauth2_client_secret }}"
  data:
    - secretKey: argocd_oauth2_client_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: argocd-oauth2-client-secret
        metadataPolicy: None
        nullBytePolicy: Ignore
