apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-webhook-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        webhook.github.secret: "{{ .secret }}"
  data:
    - secretKey: secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: argocd-github-webhook-secret
        metadataPolicy: None
        nullBytePolicy: Ignore
