apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Core
  - project-infra.yaml
  - project-apps.yaml
  - github-webhook-secret.yaml

  # Networking
  - httproute.yaml

  # Metrics
  - metrics-servicemonitor.yaml

  # SSO
  - authentik-secret.yaml
