apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  sourceRepos:
    - https://github.com/ErasmusAndre/erasmus.works.git
    - https://charts.goauthentik.io
    - ghcr.io/immich-app/immich-charts
    - https://nextcloud.github.io/helm/
  destinations:
    - namespace: apps
      server: https://kubernetes.default.svc
    - namespace: app-homepage
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
