apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-admin
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nextcloud-admin
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        nextcloud-username: admin
        nextcloud-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nextcloud-admin-password
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-postgres-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nextcloud-postgres-auth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      data:
        username: nextcloud
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nextcloud-postgres-password
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-postgres-connection
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nextcloud-postgres-connection
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        username: nextcloud
        password: "{{ .password }}"
        host: nextcloud-postgres-rw.app-nextcloud.svc.cluster.local
        database: nextcloud
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nextcloud-postgres-password
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-redis-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nextcloud-redis-auth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        redis-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nextcloud-redis-password
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-postgres-backup-s3
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nextcloud-postgres-backup-s3
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        ACCESS_KEY_ID: "GK119e4e1f8e8a6c9fc3a3a75c"
        ACCESS_SECRET_KEY: "{{ .access_secret_key }}"
  data:
    - secretKey: access_secret_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nextcloud-cnpg-backup-secret-access-key
        metadataPolicy: None
