apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-admin
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nextcloud-admin
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        nextcloud-username: admin
        nextcloud-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nextcloud-admin-password
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-postgres-auth
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nextcloud-postgres-auth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      data:
        username: nextcloud
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nextcloud-postgres-password
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-postgres-connection
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nextcloud-postgres-connection
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        username: nextcloud
        password: "{{ .password }}"
        host: nextcloud-postgres-rw.apps.svc.cluster.local
        database: nextcloud
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nextcloud-postgres-password
        metadataPolicy: None
