apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-nextcloud
resources:
  # Core
  - externalsecrets.yaml
  - postgres.yaml

  # Storage
  - pvc.yaml
  - volsync.yaml

  # Networking
  - networkpolicy.yaml
  - backendtrafficpolicy.yaml
  - httproute.yaml
