apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  monitoring:
    enablePodMonitor: true
  storage:
    size: 15Gi
    storageClass: longhorn
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-nextcloud
      endpointURL: http://garage.garage.svc.cluster.local:3900
      serverName: nextcloud-postgres
      s3Credentials:
        accessKeyId:
          name: nextcloud-postgres-backup-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: nextcloud-postgres-backup-s3
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
    retentionPolicy: "30d"
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
      secret:
        name: nextcloud-postgres-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nextcloud-postgres-backup
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  schedule: "0 15 3 * * *" # every day at 3:15am
  immediate: true
  backupOwnerReference: cluster
  cluster:
    name: nextcloud-postgres
