nextcloud:
  host: nextcloud.erasmus.works
  existingSecret:
    enabled: true
    secretName: nextcloud-admin
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password
  trustedDomains:
    - nextcloud.erasmus.works
    - nextcloud.homelab
  extraEnv:
    - name: TRUSTED_PROXIES
      value: 10.244.0.0/16
    - name: OVERWRITEHOST
      value: nextcloud.erasmus.works
    - name: OVERWRITECLIURL
      value: https://nextcloud.erasmus.works
    - name: APACHE_BODY_LIMIT
      value: "0"
    - name: PHP_UPLOAD_LIMIT
      value: 10G
    - name: PHP_MEMORY_LIMIT
      value: 1G
  extraInitContainers:
    - name: wait-for-postgres
      image: busybox:1.37
      command:
        - sh
        - -c
        - until nc -z nextcloud-postgres-rw.app-nextcloud.svc.cluster.local 5432; do sleep 2; done
  defaultConfigs:
    reverse-proxy.config.php: true
    redis.config.php: true
    autoconfig.php: true
    smtp.config.php: false
    s3.config.php: false
    swift.config.php: false
  phpConfigs:
    uploads.ini: |
      post_max_size=10G
      upload_max_filesize=10G
      max_input_time=3600
      max_execution_time=3600
      output_buffering=0
  configs:
    proxy.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_proxies' =>
        array (
          0 => '10.244.0.0/16',
        ),
        'forwarded_for_headers' =>
        array (
          0 => 'HTTP_X_FORWARDED_FOR',
        ),
      );

phpClientHttpsFix:
  enabled: true
  protocol: https

cronjob:
  enabled: true

internalDatabase:
  enabled: false

mariadb:
  enabled: false

postgresql:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  existingSecret:
    enabled: true
    secretName: nextcloud-postgres-connection
    usernameKey: username
    passwordKey: password
    hostKey: host
    databaseKey: database

redis:
  enabled: true
  architecture: standalone
  auth:
    existingSecret: nextcloud-redis-auth
    existingSecretPasswordKey: redis-password
  master:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

persistence:
  enabled: true
  existingClaim: nextcloud-html

resources:
  requests:
    cpu: 100m
    memory: 256Mi
