apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-html-restic-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nextcloud-html-restic-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        RESTIC_REPOSITORY: /mnt/repo/nextcloud-html
        RESTIC_PASSWORD: "{{ .restic_password }}"
  data:
    - secretKey: restic_password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: volsync-restic-password
        metadataPolicy: None
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: nextcloud-html
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  sourcePVC: nextcloud-html
  trigger:
    schedule: "15 3 * * *" # Every day at 3:15 AM
  restic:
    repository: nextcloud-html-restic-config
    copyMethod: Direct
    pruneIntervalDays: 7
    cacheCapacity: 2Gi
    retain:
      daily: 7
      weekly: 4
      monthly: 3
    moverVolumes:
      - mountPath: repo
        volumeSource:
          persistentVolumeClaim:
            claimName: volsync-repository
