apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 82.10.3
    helm:
      releaseName: kube-prometheus-stack
      values: |
        grafana:
          admin:
            existingSecret: kube-prometheus-stack-grafana
            userKey: admin-user
            passwordKey: admin-password
          plugins:
            - victoriametrics-logs-datasource 0.26.3
          persistence:
            enabled: true
            type: pvc
            storageClassName: longhorn
            accessModes:
              - ReadWriteOnce
            size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: kube-prometheus-stack-grafana
      namespace: monitoring
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
