apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-victorialogs
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/part-of: kube-prometheus-stack
data:
  victorialogs-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: VictoriaLogs
        type: victoriametrics-logs-datasource
        uid: victorialogs
        access: proxy
        url: http://victorialogs.monitoring.svc.cluster.local:9428
        isDefault: false
