apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      name: nextcloud-html
      namespace: app-nextcloud
      jsonPointers:
        - /spec/volumeName
    - group: postgresql.cnpg.io
      kind: Cluster
      name: nextcloud-postgres
      namespace: app-nextcloud
      jsonPointers:
        - /spec/bootstrap
  source:
    repoURL: https://github.com/ErasmusAndre/erasmus.works.git
    targetRevision: main
    path: kubernetes/apps/nextcloud
  destination:
    server: https://kubernetes.default.svc
    namespace: app-nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
