apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://charts.longhorn.io/
    chart: longhorn
    targetRevision: v1.10.1
    helm:
      releaseName: longhorn
      values: |
        defaultSettings:
          defaultDataPath: /var/lib/longhorn
          defaultReplicaCount: 1
          storageReservedPercentageForDefaultDisk: 30
        csi:
          attacherReplicaCount: 1
          provisionerReplicaCount: 1
          resizerReplicaCount: 1
          snapshotterReplicaCount: 1
        preUpgradeChecker:
          jobEnabled: false
        persistence:
          defaultClassReplicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
