defaultSettings:
  concurrentAutomaticEngineUpgradePerNodeLimit: 1
  defaultDataPath: /var/lib/longhorn
  defaultReplicaCount: 2
  storageReservedPercentageForDefaultDisk: 30
csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1
preUpgradeChecker:
  jobEnabled: false
persistence:
  defaultClassReplicaCount: 2
