apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd/application.yaml
  - infra/application.yaml
  - homepage/application.yaml
  - docmost/application.yaml
  - immich/application.yaml
  - nextcloud/application.yaml
